[package]
name = "rinadown_engine_protocol"
version = "0.1.0"
edition.workspace = true

[dependencies]
rinadown_engine = { version = "0.1.0", path = "../engine", default-features = false }
rinadown_protocol = { version = "0.1.0", path = "../protocol" }

[features]
default = []
plugins = ["rinadown_engine/plugins"]
components = ["rinadown_engine/components"]

[lints]
workspace = true

[dev-dependencies]
serde_json = "1"
